### ISSUE TITLE
Upgrade Sentry SDK

### ISSUE THREAD

**Issue by ziajka** [GNS3/gns3-web-ui#852]
We recommend you migrate to the sentry.javascript.browser SDK so you can
update your SDK from version 3.27.2 to version 5.15.5

**Comment by piotrpekala7** [comment]
@ziajka should I change version in package.json?

**Comment by piotrpekala7** [comment]
I don't understand what this is about

**Comment by grossmj** [comment]
This is how the web-ui can send crash reports to the Sentry website. The old package is raven-js (https://docs.sentry.io/clients/javascript/) and we now need to use the new sdk client (https://docs.sentry.io/platforms/javascript/). All the raven code must be migrated to use the new sdk client.

**Comment by piotrpekala7** [comment]
I created pr https://github.com/GNS3/gns3-web-ui/pull/895

**Comment by grossmj** [comment]
PR https://github.com/GNS3/gns3-web-ui/pull/895 merged.

**Comment by grossmj** [comment]
Same issue if using a node that is configured to use the GNS3 VM without a VM configured. This time is is actually worse because the web-ui keeps waiting.

![Screenshot from 2020-07-17 18-58-56](https://user-images.githubusercontent.com/4752614/87771542-9f670a80-c85f-11ea-974f-a71abdf67842.png)

**Comment by piotrpekala7** [comment]
I fixed issues that you mentioned above in commit https://github.com/GNS3/gns3-web-ui/commit/dea33c999200dd4c2dbeb93171c92a1a8307627b

**Comment by piotrpekala7** [comment]
hard to tell if we should have more accurate error filters in our own handler

**Comment by grossmj** [comment]
I disable the DSN on Sentry to avoid using our quota since we are getting a lot of error reports that we shouldn't get.

**Comment by grossmj** [comment]
I still get this error when dropping a node that is configured to run on the GNS3 VM. https://github.com/GNS3/gns3-web-ui/issues/852#issuecomment-659994257

**Comment by grossmj** [comment]
We need to fix this before the next release.

**Comment by grossmj** [comment]
Another solution is to revert back to Raven if we cannot fix this now.

**Comment by piotrpekala7** [comment]
Firstly I disabled report dialog

**Comment by piotrpekala7** [comment]
> I disable the DSN on Sentry to avoid using our quota since we are getting a lot of error reports that we shouldn't get.

I did not find information why this is happening, what I can do quickly is to expand the group of errors (e.g. by status) that will not be reported, but I have not found a reliable source of information on how it should be filtered

**Comment by piotrpekala7** [comment]
What is your opinion, should we undo the changes?

**Comment by grossmj** [comment]
> What is your opinion, should we undo the changes?

Much less annoying without the report dialog. Let's monitor the events we get and try to filter this information.

**Comment by piotrpekala7** [comment]
Yes, I think so

**Comment by piotrpekala7** [comment]
I provided fix for this issue with not configured vmin https://github.com/GNS3/gns3-web-ui/commit/4d6678fa4d084478be63617f56b3374a3545ea15

**Comment by piotrpekala7** [comment]
I hope this filtering which is now will reduce the number of errors that should not be reported

**Comment by grossmj** [comment]
I re-enabled the DSN on Sentry. Let's this what errors we get until next release.

**Comment by piotrpekala7** [comment]
At the moment we have no new events (I mean the period from the last release): https://sentry.io/organizations/gns3/releases/2020.3.0-beta.2/?project=842726

**Comment by piotrpekala7** [comment]
I went through the ones that came up before and we have another problem - most of the unhandled errors that popped up in sentry are in edge on windows and safari on mac os: https://sentry.io/organizations/gns3/issues/1792893048/?project=842726&query=is%3Aunresolved, https://sentry.io/organizations/gns3/issues/1830335383/?project=842726&query=is%3Aunresolved, https://sentry.io/organizations/gns3/issues/1792920469/?project=842726&query=is%3Aunresolved, https://sentry.io/organizations/gns3/issues/1736125045/?project=842726&query=is%3Aunresolved

**Comment by piotrpekala7** [comment]
I have never tested GNS3 behavior on other browsers than Chrome and Firefox, from the beginning I got instructions that it is impossible for us to provide support for more browsers, but I also hoped that users do not use some of the solutions anymore

**Comment by piotrpekala7** [comment]
I will check sentry again later to verify that nothing bad is happening after the last release

**Comment by grossmj** [comment]
> At the moment we have no new events (I mean the period from the last release).

I had deactivated the DSN again because of many events we received. I re-activated it now. It would be good to change the DSN for the next release (I can take care of this).

**Comment by grossmj** [comment]
@piotrpekala7 

New DSN to replace the old one: `https://d6f2d7fc84e74b05ac017753ef7bfff5@o19455.ingest.sentry.io/842726`

https://github.com/GNS3/gns3-web-ui/blob/5aeecb08a180273b6e88ba52f53b07e1d3511638/src/app/common/error-handlers/sentry-error-handler.ts#L12

Next release I will deactivate the old DSN completely.

**Comment by piotrpekala7** [comment]
ok, I created pr with this change https://github.com/GNS3/gns3-web-ui/pull/965

**Comment by piotrpekala7** [comment]
should I merge it into master branch?

**Comment by grossmj** [comment]
Yes, go ahead and merge.

**Comment by piotrpekala7** [comment]
https://github.com/GNS3/gns3-web-ui/pull/965 merged
